apiVersion: v2
name: stressed-pod
description: A Helm chart for deploying Stressed Pod - a Kubernetes pod testing tool
type: application
home: https://github.com/SQuent/helm-charts
sources:
  - https://github.com/SQuent/stressed-pod
maintainers:
  - name: Quentin SALLIO
    email: q.sallio@gmail.com
keywords:
  - Kubernetes
  - testing
  - api
version: 1.0.0
appVersion: "1.0.0" 